[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anyforecast-datasets"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = ["pandas>=1.0.0"]
